### ISSUE TITLE
DCGAN with images larger than 32x32

### ISSUE THREAD

**Issue by dnvnxg** [torchgan/torchgan#150]
**Describe the bug**
Getting the following error when trying to train on images of size larger than 32x32:
"RuntimeError: shape '[64]' is invalid for input of size 1600"

**To Reproduce**
My hyperparameters for the networks as well as the data I am loading are below
```data_dir = "dataset/images/"
tfs = transforms.Compose([
    transforms.Resize(64),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])
train_dataset = torchvision.datasets.ImageFolder(root=data_dir+"train", transform=tfs)
val_dataset = torchvision.datasets.ImageFolder(root=data_dir+"/val", transform=tfs)
test_dataset = torchvision.datasets.ImageFolder(root=data_dir+"/test", transform=tfs)

dataset = train_dataset

dataloader = torch.utils.data.DataLoader(dataset, batch_size=64, shuffle=True, num_workers=4)


dcgan_network = {
    "generator": {
        "name": DCGANGenerator,
        "args": {
            "encoding_dims": 100,
            "out_channels": 3,
            "step_channels": 64,
            "nonlinearity": nn.LeakyReLU(0.2),
            "last_nonlinearity": nn.Tanh(),
        },
        "optimizer": {"name": Adam, "args": {"lr": 0.0001, "betas": (0.5, 0.999)}},
    },
    "discriminator": {
        "name": DCGANDiscriminator,
        "args": {
            "in_channels": 3,
            "step_channels": 64,
            "nonlinearity": nn.LeakyReLU(0.2),
            "last_nonlinearity": nn.LeakyReLU(0.2),
        },
        "optimizer": {"name": Adam, "args": {"lr": 0.0003, "betas": (0.5, 0.999)}},
    },
}```

**Expected behavior**
Normal training as usual

**Installation**
- Conda

**Comment by egebeysel** [comment]
Had the same problem, the shape [64] you have there comes from the batch_size though. 
The problem here is the dcgan_network configuration. DCGANGenerator has an argument named out_size and the DCGANDiscriminator has another argument named in_size. If you set these to match your image size, it should work just fine.

**Comment by egebeysel** [comment]
In this sense, I would also recommend putting these parameters to [ Tutorial 1](https://github.com/torchgan/torchgan/blob/master/tutorials/Tutorial%201.%20Introduction%20to%20TorchGAN.ipynb) since these might be easy to oversee and can be mixed up with step_channels, which I guess you did in this case

**Comment by egebeysel** [comment]
And also a quick note on my side: ImageFolder is perfectly capable of reading your dataset in a way that it distinguishes the splits of your dataset according to the folder that they are in, you dont have to create 3 seperate datasets for it. You just give data_loader the split that you want and voila.

**Comment by dnvnxg** [comment]
Worked like a charm. Thanks @egebeysel !
